---
apiVersion: v1
kind: Template
metadata:
  name: redis-ruby-template
  annotations:
    description: "Description"
    iconClass: "icon-redis"
    tags: "redis,ruby"
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      creationTimestamp:
      generation: 1
      labels:
        app: redisharu
      name: redisharu
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: redis-build
      creationTimestamp:
      labels:
        name: redis-build
    spec:
      source:
        type: Git
        git:
          uri: git://github.com/ahharu/openshift-demo
          ref: master
        contextDir: projects/redis
      strategy:
        type: Docker
        dockerStrategy:
      output:
        to:
          kind: ImageStreamTag
          name: redisharu:latest
      resources: {}
    status:
      lastVersion: 0